// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_langevinSSM_TMBExports
#include <TMB.hpp>
#include "langevinSSM.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "langevinSSM") {
    return langevinSSM(this);
  } else {
    Rf_error("Unknown model.");
  }
  return 0;
}
