library(tidyverse)
library(terra)
library(viridis)
library(ggplot2)
library(Rcpp)
library(aniMotum) # remotes::install_github('ianjonsen/aniMotum)
library(fields)
library(TMB)
library(future)
library(furrr)
library(langevinSSM) # remotes::install_github('bmcclintock/langevinSSM)
source("simulation/init.mu_aniMotum.R")

model <- c("underdamped","overdamped")[1]

nsims <- 100 # number of simulations
nbAnimals <- 5 # number of tracks
obsPerAnimal <- 5000 # number of simulated locations per track
timeStep <- 0.01 # time scale of simulation (should be small to help prevent discretization error)

beta <- c(-4, 6, 5, -0.1) # resource selection coefficients for the spatial covariates (cov_1, cov_2, ... cov_ncov, d2c)
ncov <- length(beta) - 1 # number of spatial covariates to be generated using simCov
sigma <- 5 # diffusion (or speed) parameter
gamma <- 0.5 # friction parameter (smaller value -> more directional persistence); ignored unless model=="underdamped"
psi <- 1 # error ellipse scaling parameter

useInitialValues <- TRUE # logical indicating whether or not to use initial values generated by langevinSSM::initialValues
initialInner <- TRUE # logical indicating whether or not to use an initial inner optimization for the random effects (``mu'' and/or ``vel'') before optimizing over all parameters
map <- list(psi=factor(NA)) # map for fixing parameters

## sampling rate, missing data, and measurement error
samplingRate <- 1 # for subsampling observations from true continuous-time model (e.g. if samplingRate = 2 then data are roughly thinned by 2); must be >= 1; note bias increases with samplingRate, but relationships largely preserved
propMissing <- 0 # proportion of missing observations; passed as NA observations to TMB (so corresponding true locations treated as random effects to be estimated)
use_aniMotum <- FALSE # logical indicating whether or not to use aniMotum to impute missing locations; if FALSE, langevinSSM uses linear interpolation

smaj.sd <- 1.5 # SD for semi-major error ellipse axis; smaj ~ abs(Normal(0,smaj.sd))
smin.sd <- smaj.sd/2 # SD for semi-minor error ellipse axis; smin ~ abs(Normal(0,smin.sd))
eor.lim <- c(0,180) # range for error ellipse orientation (in degrees from north); eor ~ Uniform(eor.lim[1],eor.lim[2])
measurementError <- list(smaj.sd=smaj.sd,smin.sd=smin.sd,eor.lim=eor.lim) # setting measurementError <- NULL adds no measurement error to observations

## specify scale and spatial autocorrelation for covariates
sca <- 200 # bounding box scale
covRange <- c(0.1,0.5) # lower and upper bounds for covariate spatial range parameter (lower has less spatial autocorrelation)
covTimes <- 1 # number of time-varying covariate layers (if >1, then each covariate is a SpatRaster with covTimes layers; if 1, then each covariate is a single-layer SpatRaster)
ztimes <- seq(0,obsPerAnimal*timeStep,length=covTimes) # z (i.e. time) values for raster stacks

## smooth gradient specifications (based on adjacent cells)
## slows model fitting, but can potentially reduce bias if \Delta_t is large (i.e. samplingRate > 1) relative to timeStep (Blackwell & Matthiopoulos 2024, https://doi.org/10.1002/ecy.4457) or if measurement error is large relative to raster cell resolution
npoints <- 0 # number of smoothing points around current cell (0 = none, 4 = diagonal, 8 = queen neighborhood);
curweight <- 1/2 # smoothing weight of current cell location; ignored if npoints=0
weights <- c(curweight,rep((1-curweight)/npoints,npoints)) # smoothing weights (must be of length 5 or 9 and sum to 1); ignored if npoints=0
zetaScale <- 2 # scale factor for smooth gradient neighborhood (>1 increases, <1 decreases neighborhood); underdamped Langevin neighborhood = zetaScale * sqrt(2*pi) * sigma; overdamped langevin neighborhood = zetaScale * sigma / sqrt(2); ignored if npoints=0

langSim <- subDat <- langFit <- list()
spatialCovs <- list()
parMat <- matrix(NA,nrow=nsims,6+ifelse(model=="underdamped",1,0))
if(model=="overdamped"){
  colnames(parMat) <- c(paste0("beta",1:(ncov+1)),"sigma","BA")
} else colnames(parMat) <- c(paste0("beta",1:(ncov+1)),"sigma","gamma","BA")

dataName <- paste0(model,"_nbAnimals",nbAnimals,"_obsPerAnimal",obsPerAnimal,"_timeStep",timeStep,"","_beta",paste0(beta,collapse = "_"),"_sigma",sigma,"_gamma",gamma,"_sca",sca,"_covRange",paste0(covRange,collapse="_"),
                   ifelse(covTimes>1,paste0("_covTimes",covTimes),""))

set.seed(1,kind="Mersenne-Twister",normal.kind = "Inversion")
if(!file.exists(paste0("simulation/data/",dataName,".RData"))){
  for(isim in 1:nsims){
    cat("Simulation",isim,"\n")
    #######################
    ## Define covariates ##
    #######################
    # Generate ncov spatial covariates
    message("   Generating covariates...")

    covNames <- c("cov1","cov2","cov3","d2c")
    spatialCovs[[isim]] <- list()

    for(i in 1:ncov) {
      spatialCovs[[isim]][[i]] <- list()
      if(covTimes>1){
        for(ztime in 1:length(ztimes)){
          irange <- runif(1,covRange[1],covRange[2])
          spatialCovs[[isim]][[i]][[ztime]] <- simCov(sca = sca, irange=irange, sigma2 = 0.1, kappa = 0.5)
          terra::time(spatialCovs[[isim]][[i]][[ztime]]) <- ztimes[ztime]
          names(spatialCovs[[isim]][[i]][[ztime]]) <- covNames[i]
          # terra::crs(spatialCovs[[isim]][[i]]) <- "epsg:3416"
        }
        spatialCovs[[isim]][[i]] <- terra::rast(spatialCovs[[isim]][[i]])
      } else {
        irange <- runif(1,covRange[1],covRange[2])
        spatialCovs[[isim]][[i]] <- simCov(sca = sca, irange=irange, sigma2 = 0.1, kappa = 0.5)
        names(spatialCovs[[isim]][[i]]) <- paste0("cov",i)
        # terra::crs(spatialCovs[[isim]][[i]]) <- "epsg:3416"
      }
    }

    coords <- terra::crds(spatialCovs[[isim]][[1]])
    dist2 <- (coords[, "x"]^2 + coords[, "y"]^2) / sca

    spatialCovs[[isim]][[4]] <- terra::setValues(spatialCovs[[isim]][[1]][[1]], dist2)
    names(spatialCovs[[isim]][[4]]) <- covNames[4]
    names(spatialCovs[[isim]]) <- covNames

    if(model=="underdamped"){
      par <- list(beta=beta,sigma=sigma,gamma=gamma,psi=psi)
    } else {
      par <- list(beta=beta,sigma=sigma,psi=psi)
    }

    # simulate "high resolution" tracks; this can take a while...
    langSim[[isim]] <- tryCatch(stop(),error=function(e) e)
    while(inherits(langSim[[isim]],"error")){
      langSim[[isim]] <- tryCatch(simLangevin(
        model = model,
        nbAnimals = nbAnimals,
        obsPerAnimal = obsPerAnimal,
        timeStep = timeStep,
        par=par,
        spatialCovs = spatialCovs[[isim]]
      ),error=function(e) e)
      if(inherits(langSim[[isim]],"error")){
        message("    Retrying Simulation ",isim,": ",langSim[[isim]]$message)
      }
    }
  }
  # Inside your simulation loop, right before save()
  if(!dir.exists("simulation/data")) dir.create("simulation/data")

  # Wrap the SpatRasters for safe saving
  spatialCovs_wrapped <- list()
  for(isim in 1:length(spatialCovs)) {
    spatialCovs_wrapped[[isim]] <- list()
    for(i in 1:length(spatialCovs[[isim]])) {
      spatialCovs_wrapped[[isim]][[i]] <- terra::wrap(spatialCovs[[isim]][[i]])
    }
    names(spatialCovs_wrapped[[isim]]) <- names(spatialCovs[[isim]])
  }
  # Save the wrapped version
  save(langSim, spatialCovs_wrapped, file=paste0("simulation/data/", dataName, ".RData"))
} else {
  load(paste0("simulation/data/",dataName,".RData"))

  # Unwrap the saved rasters back into SpatRaster objects
  spatialCovs <- list()
  for(isim in 1:length(spatialCovs_wrapped)) {
    spatialCovs[[isim]] <- list()
    for(i in 1:length(spatialCovs_wrapped[[isim]])) {
      spatialCovs[[isim]][[i]] <- terra::unwrap(spatialCovs_wrapped[[isim]][[i]])
    }
    names(spatialCovs[[isim]]) <- names(spatialCovs_wrapped[[isim]])
  }
}

# add measurement error
set.seed(1, kind="Mersenne-Twister", normal.kind = "Inversion")
for(isim in 1:nsims){
  subDat[[isim]] <- addMeasurementError(langSim[[isim]], measurementError = measurementError)
}

# subsample data
set.seed(1, kind="Mersenne-Twister", normal.kind = "Inversion")
for(isim in 1:nsims){
  subDat[[isim]] <- subSampleData(subDat[[isim]], samplingRate = samplingRate, propMissing = propMissing)
}

for(isim in 1:nsims){
  cat("Simulation",isim,"\n")
  # Compute utilization distribution
  UD <- getUD(spatialCovs[[isim]], beta=beta, log=TRUE, plot=FALSE)

  # Plot covariates
  ggtheme <- theme(axis.title = element_text(size=12), axis.text = element_text(size=12),
                   legend.title = element_text(size=12), legend.text = element_text(size=12))
  c1plot <- plotRaster(spatialCovs[[isim]][[1]], legend.title = expression(c[1])) + ggtheme
  c2plot <- plotRaster(spatialCovs[[isim]][[2]], legend.title = expression(c[2])) + ggtheme
  c3plot <- plotRaster(spatialCovs[[isim]][[3]], legend.title = expression(c[3])) + ggtheme
  UDplot <- plotRaster(UD, legend.title = expression(pi)) + ggtheme

  # generate missing data using aniMotum
  if(propMissing>0 && any(is.na(subDat[[isim]]$x))){
    if(use_aniMotum){
      message("   Fitting aniMotum separately to each track...")
      notNA <- which(!is.na(subDat[[isim]]$x))
      future::plan(future::multisession,workers=min(nbAnimals,parallel::detectCores()-1))  # workers sets number of cores to use
      init.mu <- init.mu_aniMotum(subDat[[isim]][notNA,],model="rw",timeSteps=data.frame(id=as.character(subDat[[isim]]$id),date=as.POSIXlt(subDat[[isim]]$date * 1000))) # fit_ssm doesn't like very small \Delta_t
      #init.mu <- subDat[[isim]][,c("mu.x","mu.y")] # true values
      par$mu=init.mu

      if(model=="underdamped"){
        init.vel <- matrix(0,nrow(subDat[[isim]]),2)
        #init.vel <- subDat[[isim]][,c("vel.x","vel.y")] # true values
        par$vel = init.vel
      }
    }
  }

  if(useInitialValues) par <- initialValues(subDat[[isim]],model,par=list(psi=psi),spatialCovs=spatialCovs[[isim]])

  langFit[[isim]] <- suppressMessages(fitLangevin(subDat[[isim]],model=model,par=par,spatialCovs=spatialCovs[[isim]],
                                 map=map,
                                 smoothGradient = ifelse(npoints>0,TRUE,FALSE), npoints = npoints, curweight = curweight, zetaScale = zetaScale,
                                 silent=TRUE, control=list(trace=0),initialInner=initialInner))

  parMat[isim,1:(5+ifelse(model=="underdamped",1,0))] <- langFit[[isim]]$par
  parMat[isim,"sigma"] <- langFit[[isim]]$estimates$natural["sigma",1]
  if(model=="underdamped") parMat[isim,"gamma"] <- langFit[[isim]]$estimates$natural["gamma",1]

  zoom_ext <- terra::ext(-100, 100, -100, 100)

  par(mfrow=c(2,2))
  plot(UD[[1]], main = paste0("Simulation ", isim), col = viridis::viridis(100))
  points(subDat[[isim]]$x, subDat[[isim]]$y, col = 2) # observed locations
  for(i in 1:nbAnimals) {
    lines(langSim[[isim]]$mu.x[langSim[[isim]]$id==i], langSim[[isim]]$mu.y[langSim[[isim]]$id==i]) # true path
  }
  plot(subDat[[isim]]$x,subDat[[isim]]$y,col=2,asp=1) # observed locations
  for(i in 1:nbAnimals){
    lines(langFit[[isim]]$report$mu[1,subDat[[isim]]$id==i],langFit[[isim]]$report$mu[2,subDat[[isim]]$id==i],type="o",pch=20,col=3) # estimated path
  }
  for(i in 1:nbAnimals){
    lines(langSim[[isim]]$mu.x[langSim[[isim]]$id==i],langSim[[isim]]$mu.y[langSim[[isim]]$id==i]) # true path
  }
  plot(terra::crop(UD,zoom_ext),main="True UD",col=viridis::viridis(100))
  estUD <- suppressMessages(getUD(spatialCovs[[isim]],langFit[[isim]],log=TRUE,plot=FALSE))
  plot(terra::crop(estUD$log_UD,zoom_ext),main="Estimated UD",col=viridis::viridis(100))

  parMat[isim,"BA"] <- mean(rasterOverlap(exp(estUD),exp(UD))) # Calculate Bhattacharyya's Affinity between estimated and true UDs

  print(paste0("            ",paste0(colnames(parMat),collapse="    ")))
  print(paste0("current ",paste0(round(parMat[isim,],6),collapse=" ")))
  print(paste0("overall ",paste0(round(apply(parMat[1:isim,,drop=FALSE],2,mean),6),collapse=" ")))

}

if(!dir.exists("simulation/results")) dir.create("simulation/results")
save(parMat,beta,sigma,gamma,obsPerAnimal,subDat,langFit,psi,timeStep,samplingRate,propMissing,measurementError,sca,npoints,curweight,covRange,map,useInitialValues,covTimes,file=paste0("simulation/results/",dataName,"_psi",psi,ifelse(!is.null(measurementError),paste0("_smaj",measurementError$smaj.sd,"_smin",measurementError$smin.sd,"_eor",paste0(measurementError$eor.lim,collapse="_")),""),"_samplingRate",samplingRate,"_propMissing",propMissing,"_aniMotum",use_aniMotum,"_npoints",npoints,"_curweight",curweight,"_zetaScale",zetaScale,".RData"))
