// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// simulate_langevin_cpp
DataFrame simulate_langevin_cpp(int model, int nbAnimals, int obsPerAnimal, NumericVector dt_vec, double gamma, double sigma, NumericVector beta, List raster_data, NumericMatrix initialPosition);
RcppExport SEXP _langevinSSM_simulate_langevin_cpp(SEXP modelSEXP, SEXP nbAnimalsSEXP, SEXP obsPerAnimalSEXP, SEXP dt_vecSEXP, SEXP gammaSEXP, SEXP sigmaSEXP, SEXP betaSEXP, SEXP raster_dataSEXP, SEXP initialPositionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type model(modelSEXP);
    Rcpp::traits::input_parameter< int >::type nbAnimals(nbAnimalsSEXP);
    Rcpp::traits::input_parameter< int >::type obsPerAnimal(obsPerAnimalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dt_vec(dt_vecSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< List >::type raster_data(raster_dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type initialPosition(initialPositionSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_langevin_cpp(model, nbAnimals, obsPerAnimal, dt_vec, gamma, sigma, beta, raster_data, initialPosition));
    return rcpp_result_gen;
END_RCPP
}
// measurementError_rcpp
List measurementError_rcpp(DataFrame data, double smaj_sd, double smin_sd, NumericVector eor, double psi, bool knownError);
RcppExport SEXP _langevinSSM_measurementError_rcpp(SEXP dataSEXP, SEXP smaj_sdSEXP, SEXP smin_sdSEXP, SEXP eorSEXP, SEXP psiSEXP, SEXP knownErrorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type smaj_sd(smaj_sdSEXP);
    Rcpp::traits::input_parameter< double >::type smin_sd(smin_sdSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eor(eorSEXP);
    Rcpp::traits::input_parameter< double >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< bool >::type knownError(knownErrorSEXP);
    rcpp_result_gen = Rcpp::wrap(measurementError_rcpp(data, smaj_sd, smin_sd, eor, psi, knownError));
    return rcpp_result_gen;
END_RCPP
}
// measurementError_LS_rcpp
List measurementError_LS_rcpp(DataFrame data, double x_sd, double y_sd, double tau_x, double tau_y, double rho_o, bool knownError);
RcppExport SEXP _langevinSSM_measurementError_LS_rcpp(SEXP dataSEXP, SEXP x_sdSEXP, SEXP y_sdSEXP, SEXP tau_xSEXP, SEXP tau_ySEXP, SEXP rho_oSEXP, SEXP knownErrorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type x_sd(x_sdSEXP);
    Rcpp::traits::input_parameter< double >::type y_sd(y_sdSEXP);
    Rcpp::traits::input_parameter< double >::type tau_x(tau_xSEXP);
    Rcpp::traits::input_parameter< double >::type tau_y(tau_ySEXP);
    Rcpp::traits::input_parameter< double >::type rho_o(rho_oSEXP);
    Rcpp::traits::input_parameter< bool >::type knownError(knownErrorSEXP);
    rcpp_result_gen = Rcpp::wrap(measurementError_LS_rcpp(data, x_sd, y_sd, tau_x, tau_y, rho_o, knownError));
    return rcpp_result_gen;
END_RCPP
}
// simulate_regionprob_cpp
arma::mat simulate_regionprob_cpp(int nSims, int n_cells, int n_layers, int n_covs, const arma::mat& beta_draws, const Rcpp::List& cov_mats_list, const arma::mat& mask_mat, bool show_progress);
RcppExport SEXP _langevinSSM_simulate_regionprob_cpp(SEXP nSimsSEXP, SEXP n_cellsSEXP, SEXP n_layersSEXP, SEXP n_covsSEXP, SEXP beta_drawsSEXP, SEXP cov_mats_listSEXP, SEXP mask_matSEXP, SEXP show_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nSims(nSimsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cells(n_cellsSEXP);
    Rcpp::traits::input_parameter< int >::type n_layers(n_layersSEXP);
    Rcpp::traits::input_parameter< int >::type n_covs(n_covsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta_draws(beta_drawsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type cov_mats_list(cov_mats_listSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mask_mat(mask_matSEXP);
    Rcpp::traits::input_parameter< bool >::type show_progress(show_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_regionprob_cpp(nSims, n_cells, n_layers, n_covs, beta_draws, cov_mats_list, mask_mat, show_progress));
    return rcpp_result_gen;
END_RCPP
}
// simulate_ud_cpp
Rcpp::List simulate_ud_cpp(int nSims, int n_cells, int n_ud_layers, int n_covs, const arma::mat& beta_draws, const Rcpp::List& cov_mats_list, bool show_progress);
RcppExport SEXP _langevinSSM_simulate_ud_cpp(SEXP nSimsSEXP, SEXP n_cellsSEXP, SEXP n_ud_layersSEXP, SEXP n_covsSEXP, SEXP beta_drawsSEXP, SEXP cov_mats_listSEXP, SEXP show_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nSims(nSimsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cells(n_cellsSEXP);
    Rcpp::traits::input_parameter< int >::type n_ud_layers(n_ud_layersSEXP);
    Rcpp::traits::input_parameter< int >::type n_covs(n_covsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta_draws(beta_drawsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type cov_mats_list(cov_mats_listSEXP);
    Rcpp::traits::input_parameter< bool >::type show_progress(show_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_ud_cpp(nSims, n_cells, n_ud_layers, n_covs, beta_draws, cov_mats_list, show_progress));
    return rcpp_result_gen;
END_RCPP
}
