#' Format data for \code{\link{fitLangevin}}
#'
#' \code{formatData} takes a data frame or \code{sf} object containing tracking data and formats it for use with the \code{\link{fitLangevin}} function. It is a modified version of the \code{format_data} function from the \href{https://ianjonsen.github.io/aniMotum/}{aniMotum} package.
#'
#' @param data A data frame or \code{\link[sf]{sf}} object containing the tracking data to be formatted. The data must contain columns for the animal ID (``id''), date/time (``date''), location quality class (``lc''; if applicable), coordinates (``coord''), and measurement error (``epar'' and/or ``sderr''; if applicable). The column names can be specified using the corresponding arguments of this function.
#' @param id Character string specifying the column name for the animal ID. Default: ``id''.
#' @param date Character string specifying the column name for the date/time, which must be of class \code{\link{DateTimeClasses}} or a character string parseable to a date/time (e.g., "YYYY-MM-DD HH:MM:SS"). Default: ``date''.
#' @param coord Character vector of length 2 specifying the column names for the (projected) coordinates. Default: c("x", "y").
#' @param lc Character string specifying the column name for the location quality class. Default: ``lc''.
#' @param epar Character vector of length 3 specifying the column names for the error ellipse parameters (semi-major axis, semi-minor axis, and error ellipse orientation). See Details. Default: c("smaj", "smin", "eor").
#' @param sderr Character vector of length 2 specifying the column names for the standard deviations of the error for the x and y coordinates. Default: c("x.err", "y.err").
#' @param emf An optional data frame containing error multiplication factors (or standard deviations) for location quality classes. Must contain columns \code{lc}, \code{emf.x}, and \code{emf.y} (see \code{\link{getEMF}}). If provided, these values will be used to fill in \code{x.err} and \code{y.err} for observations where neither error ellipse (``epar'') nor standard deviations (``sderr'') information is provided in \code{data}. Default: \code{NULL}.
#' @param predTimes An optional data frame containing custom times at which to predict the animal's location. Must contain columns corresponding to the \code{id} and \code{date} arguments. If provided, the returned \code{dataLangevin} object will be padded with these dates, leaving all columns (such as coordinates and errors) as \code{NA}. See Details. Default: \code{NULL}.
#' @param time.unit Character string specifying the time unit for the time steps. Default: ``hours''.
#' @param tz Character string specifying the time zone for the date/time column. Default: ``UTC''.
#' @return A data frame of class \code{dataLangevin} containing the formatted tracking data. The data frame contains the following columns:
#' \item{id}{Animal ID}
#' \item{date}{Date/time of observation}
#' \item{dt}{Numeric time step between observations (in \code{time.unit}). One generally does not want \code{dt} to be too big or too small (as this can cause numerical issues during optimization), so select \code{time.unit} with care. \strong{If any \code{dt < 1.e-6}, then \code{\link{fitLangevin}} assumes there is no change in the movement state (i.e., position and velocity) during these extremely short time steps.}}
#' \item{x}{x-coordinate of the location}
#' \item{y}{y-coordinate of the location}
#' \item{lc}{Location quality class (if applicable)}
#' \item{smaj}{Semi-major axis of the error ellipse}
#' \item{smin}{Semi-minor axis of the error ellipse}
#' \item{eor}{Error ellipse orientation (in radians)}
#' \item{x.err}{Standard deviation of the x-coordinate error}
#' \item{y.err}{Standard deviation of the y-coordinate error}
#'
#' @details
#' \strong{Coordinate Systems and Units:}
#' The coordinates \strong{must be projected to a metric coordinate system} (i.e., not longitude/latitude). For error ellipse data, the columns specified in \code{epar} should contain the semi-major axis (on the same scale as the coordinates), semi-minor axis (on the same scale as the coordinates), and error ellipse orientation (in \strong{degrees from north}). \strong{\code{formatData} automatically converts the orientation from degrees to radians (unless \code{data} is a \code{simLangevin} object generated by \code{\link{simLangevin}})}.
#' For x- and y-axis error data, the columns specified in \code{sderr} should contain the standard deviations of the errors for the x and y coordinates (on the same scale as the coordinates).
#'
#' \strong{Location Classes and Measurement Errors:}
#' \code{formatData} is highly flexible in how it handles measurement error information. Observations can have error ellipses (``epar''), standard deviations (``sderr''), missing errors that are automatically filled based on location quality class (``lc'') using \code{emf} (see \code{\link{getEMF}}), or no measurement error. Location quality classes (``lc'') are used to determine which observations have unknown errors that need to be filled using \code{emf}. These classes can include Argos Least Squares (3, 2, 1, 0, A, B, Z), GPS or Argos Kalman Filter (G), and Generic Locations (GL). The handling of measurement error for each type of location quality class is as follows:
#' \itemize{
#'   \item \strong{Argos Least Squares (3, 2, 1, 0, A, B, Z):} Typically lack explicit error parameters. If missing, these can be filled using the \code{emf} argument (see \code{\link{getEMF}}). However, if users explicitly provide error ellipses or standard deviations for any given observation in \code{data}, the user-specified values are preserved and \code{emf} filling is bypassed for this particular observation.
#'   \item \strong{GPS or Argos Kalman Filter (G):} Can be provided with error ellipses, standard deviations, or no errors (which will be filled by the \code{emf} table if provided).
#'   \item \strong{Generic Locations (GL):} Locations where standard deviations (\code{x.err}, \code{y.err}) are explicitly provided by the user. If \code{emf} is specified but no \code{x.err} and \code{y.err} are provided, these rows are not filled unless \code{emf} includes an entry for \code{GL} (otherwise an error is returned).
#'   \item \strong{No Measurement Error:} If the \code{emf} argument is \code{NULL} (the default), observations with \code{NA} for all \code{epar} columns and \code{NA} for all \code{sderr} columns are assumed to have no measurement error. Their existing location class is preserved.
#' }
#'
#' \strong{Predicting Locations at Specific Times:}
#' The \code{predTimes} argument allows users to specify custom times at which they want the model to output predictions of the animal's true trajectory (e.g., to standardize the temporal resolution of the track). When formatting the data, \code{formatData} pads the dataset with these requested times, assigning \code{NA} to the coordinates and measurement error columns. During model fitting, whenever a coordinate is \code{NA} (either natively in the dataset or injected via \code{predTimes}), \code{\link{fitLangevin}} bypasses the observation error model evaluation for that time step. Instead, it relies purely on the Langevin diffusion state process model to predict the true (latent) location.
#'
#' @examples
#' # unformatDat included in package; see ?unformatDat for details
#' head(unformatDat)
#'
#' formatDat <- formatData(unformatDat, time.unit = "hours")
#' head(formatDat)
#'
#' \dontrun{
#' # exampleCovs included in package; see ?exampleCovs for details
#' fit <- fitLangevin(formatDat, spatialCovs = exampleCovs, silent=TRUE)
#' }
#' @importFrom dplyr rename arrange select all_of everything group_by ungroup filter row_number n
#' @importFrom sf st_coordinates st_drop_geometry st_is_longlat
#' @export
formatData <- function(data, id = "id", date = "date", coord = c("x", "y"), lc = "lc", epar = c("smaj", "smin", "eor"), sderr = c("x.err", "y.err"), emf = NULL, predTimes = NULL, time.unit = "hours", tz = "UTC"){

  if(inherits(data,"simLangevin") | inherits(data,"dataLangevin")) stop('data is already formatted for fitLangevin')

  if (inherits(data, "sf")) {
    if (sf::st_is_longlat(data)) {
      stop("The provided 'sf' object uses unprojected longitude/latitude coordinates. Please project your data to a metric coordinate system (e.g., using sf::st_transform) before formatting.")
    }

    coords_mat <- sf::st_coordinates(data)
    data <- sf::st_drop_geometry(data)
    data[[coord[1]]] <- coords_mat[, 1]
    data[[coord[2]]] <- coords_mat[, 2]

  } else {
    x_vals <- data[[coord[1]]]
    y_vals <- data[[coord[2]]]

    if(!inherits(data,"simLangevin")){
      if (all(x_vals >= -180 & x_vals <= 360, na.rm = TRUE) &&
          all(y_vals >= -90 & y_vals <= 90, na.rm = TRUE)) {
        warning("Coordinates appear to be unprojected longitude/latitude. Langevin models require projected coordinates (e.g., UTM). Please ensure your data is projected.")
      }
    }
  }

  if(!inherits(data[[date]],"POSIXt") && !is.character(data[[date]])) {
    stop(paste0("data$", date, " must be of class 'POSIXt' or a character string parseable to a date."))
  }

  if (!(lc %in% names(data))) {
    data[[lc]] <- NA_character_
  }

  if (!all(is.na(data[[lc]]))) {
    valid_lcs <- c("3","2","1","0","A","B","Z","G","GL")
    provided_lcs <- data[[lc]][!is.na(data[[lc]])]
    if (!all(provided_lcs %in% valid_lcs)) {
      stop("Invalid location classes detected. Allowed values: 3, 2, 1, 0, A, B, Z, G, GL.")
    }
  }

  if (!is.null(predTimes)) {
    if (!is.data.frame(predTimes)) stop("'predTimes' must be a data frame.")
    if (!all(c(id, date) %in% names(predTimes))) stop(paste0("'predTimes' must contain '", id, "' and '", date, "' columns to match 'data'."))
    if (!all(predTimes[[id]] %in% data[[id]])) stop(paste0("All track ID's in 'predTimes[[", id, "]]' must exist in 'data[[", id, "]]'."))
    is_posix <- inherits(data[[date]], "POSIXt") && inherits(predTimes[[date]], "POSIXt")
    is_char <- is.character(data[[date]]) && is.character(predTimes[[date]])
    if (!(is_posix || is_char)) {
      stop(paste0("The '", date, "' column in 'predTimes' must be of the same type (POSIXt or character) as the '", date, "' column in 'data'."))
    }
  }

  out <- format_data(x = data, id = id, date = date, coord = coord, lc = lc, epar = epar, sderr = sderr, tz = tz)

  out <- out %>%
    dplyr::rename(x = dplyr::all_of(coord[1]), y = dplyr::all_of(coord[2])) %>%
    dplyr::arrange(id, date)

  first_obs <- out[!duplicated(out$id), ]
  if(any(is.na(first_obs$x) | is.na(first_obs$y))) {
    stop("The first observation for each track in 'data' cannot have missing (NA) coordinates.")
  }

  if (!is.null(predTimes)) {
    pt_dates <- predTimes[[date]]
    if (!inherits(pt_dates, "POSIXt")) {
      pt_dates <- try(as.POSIXct(pt_dates, tz = tz), silent = TRUE)
      if (inherits(pt_dates, "try-error")) stop("'predTimes' dates must be in a standard format: YYYY-MM-DD HH:MM:SS")
    }

    pt_ids <- as.character(predTimes[[id]])

    for (uid in unique(pt_ids)) {
      first_time <- first_obs$date[first_obs$id == uid]
      if (length(first_time) > 0 && any(pt_dates[pt_ids == uid] < first_time)) {
        stop(paste0("In 'predTimes', track '", uid, "' contains dates prior to its first observation in 'data'."))
      }
    }

    pt_pad <- data.frame(id = pt_ids, date = pt_dates)
    missing_cols <- setdiff(names(out), names(pt_pad))
    for (col in missing_cols) {
      pt_pad[[col]] <- NA
    }
    pt_pad <- pt_pad[, names(out)]

    out <- rbind(out, pt_pad)
    out <- out %>% dplyr::arrange(id, date)
  }

  # --- DUPLICATE TIME HANDLING ---

  # warn if there are duplicates where both have observed (non-NA) coordinates
  obs_dups <- out %>%
    dplyr::filter(!is.na(x) & !is.na(y)) %>%
    dplyr::group_by(id, date) %>%
    dplyr::filter(dplyr::n() > 1) %>%
    dplyr::ungroup()

  if (nrow(obs_dups) > 0) {
    warning("Duplicated times with observed (non-NA) coordinates found within one or more tracks.")
  }

  # remove redundant NA coordinates at duplicated times
  out <- out %>%
    dplyr::arrange(id, date, is.na(x)) %>%
    dplyr::group_by(id, date) %>%
    dplyr::filter(!is.na(x) | dplyr::row_number() == 1) %>%
    dplyr::ungroup() %>%
    dplyr::arrange(id, date)

  # -------------------------------

  dt_list <- lapply(split(out$date, out$id), function(t) {
    c(0, as.numeric(difftime(t[-1], t[-length(t)], units = time.unit)))
  })
  out$dt <- unsplit(dt_list, out$id)

  out <- out %>% dplyr::select(id, date, dt, x, y, lc, smaj, smin, eor, x.err, y.err, dplyr::everything())

  # --- EMF INTEGRATION ---
  if (!is.null(emf)) {
    if (!is.data.frame(emf) || !all(c("lc", "emf.x", "emf.y") %in% names(emf))) {
      stop("'emf' must be a data frame containing 'lc', 'emf.x', and 'emf.y' columns.")
    }

    # Identify rows that have valid coordinates but lack ANY error information
    missing_err_idx <- which(!is.na(out$x) & !is.na(out$y) &
                               is.na(out$smaj) & is.na(out$smin) & is.na(out$eor) &
                               is.na(out$x.err) & is.na(out$y.err))

    if (length(missing_err_idx) > 0) {

      # Determine which LCs actually need filling
      lcs_to_fill <- unique(as.character(out$lc[missing_err_idx]))
      missing_lcs <- setdiff(lcs_to_fill, as.character(emf$lc))

      # Only stop if an LC that NEEDS filling is missing from the EMF table
      if (length(missing_lcs) > 0) {
        stop("The following location classes require error filling but are missing from the 'emf' table: ", paste(missing_lcs, collapse = ", "))
      }

      match_idx <- match(as.character(out$lc[missing_err_idx]), as.character(emf$lc))
      valid_matches <- !is.na(match_idx)
      update_idx <- missing_err_idx[valid_matches]

      out$x.err[update_idx] <- emf$emf.x[match_idx[valid_matches]]
      out$y.err[update_idx] <- emf$emf.y[match_idx[valid_matches]]
    }
  }

  if(!inherits(data,"simLangevin")){
    if(any(!is.na(out$eor)) && isFALSE(any(out$eor > pi, na.rm = TRUE))) {
      warning(epar[3], " values were converted to radians, but they appear to have been provided in radians rather than degrees from north. Please ensure that the ", epar[3], " column was provided in degrees from north.")
    }
    out$eor <- out$eor * pi / 180 # convert from degrees to radians
  }

  out$id <- as.factor(out$id)
  out$lc <- as.factor(out$lc)
  rownames(out) <- NULL

  checkErrorData(out, coord = c("x", "y"))

  out <- as.data.frame(out)

  out <- class_dataLangevin(out, time.unit = time.unit)

  return(out)
}
