#' Predict unobserved locations from a fitted Langevin model
#'
#' @description
#' Generates predicted locations (and velocities, for the underdamped model) along with their standard errors at unobserved times. This function works by freezing the maximum likelihood estimates of the movement and observation parameters from a previously fitted model and running a fast, iterative inner optimization to impute the latent states until convergence.
#'
#' @param fit A \code{fitLangevin} object.
#' @param data A \code{dataLangevin} object generated by \code{\link{formatData}}. To predict unobserved times, this dataset must have been formatted with the \code{predTimes} argument so that it contains padded \code{NA} observations at the desired prediction times.
#' @param spatialCovs List of named \code{\link[terra]{SpatRaster-class}} objects containing the spatial covariates. Must be the exact same list used to fit the model.
#' @param tol Numeric. The tolerance for the maximum absolute shift in spatial coordinates between iterations. Optimization stops when the maximum shift is below this value. Default: \code{1e-3}.
#' @param max_iter Integer. The maximum number of stabilization iterations allowed. Default: \code{10}.
#' @param ... Additional arguments passed to \code{\link{fitLangevin}}.
#'
#' @details
#' This function provides an efficient way to interpolate animal tracks (e.g., to a perfectly even temporal grid) after the primary model has been fitted on unpadded data. The fixed parameters are frozen and \code{TMB} iteratively evaluates the random effects, allowing for rapid imputation of the missing locations.
#'
#' Note: If the original dataset used to fit the model contained native \code{NA} coordinates, this function will simultaneously impute those missing values alongside the new \code{predTimes}.
#'
#' @return A \code{fitLangevin} object containing the updated, regularized trajectory. The structure is identical to a standard fitted model (with the addition of a \code{predLangevin} class), allowing it to be passed to \code{\link{plot.fitLangevin}} and other downstream functions.
#'
#' @export
predLangevin <- function(fit, data, spatialCovs, tol = 1e-3, max_iter = 10, ...) {

  if (missing(data) || !inherits(data, "dataLangevin")) stop("'data' must be provided and must be a formatted 'dataLangevin' object.")
  if (missing(spatialCovs) || !is.list(spatialCovs)) stop("'spatialCovs' must be provided as a list of SpatRaster objects.")
  if(!inherits(fit,"fitLangevin")) stop("'fit' must be of class 'fitLangevin'.")

  verify_signatures(fit, spatialCovs = spatialCovs)

  scaleFactor <- fit$conditions$scaleFactor
  parList <- fit$tmb_setup$parList

  par_mle <- list(
    beta = parList$beta,
    sigma = exp(parList$log_sigma) * scaleFactor
  )
  if (fit$conditions$model == "underdamped") par_mle$gamma <- exp(parList$log_gamma)

  parNames <- names(fit$par)
  if ("l_psi" %in% parNames) par_mle$psi <- exp(parList$l_psi)
  if ("l_tau" %in% parNames) par_mle$tau <- exp(parList$l_tau)
  if ("l_rho_o" %in% parNames) par_mle$rho_o <- 2 / (1 + exp(-parList$l_rho_o)) - 1

  map <- list(
    beta = factor(rep(NA, length(par_mle$beta))),
    sigma = factor(NA)
  )
  if (fit$conditions$model == "underdamped") map$gamma <- factor(NA)
  if ("psi" %in% names(par_mle)) map$psi <- factor(NA)
  if ("tau" %in% names(par_mle)) map$tau <- factor(rep(NA, length(par_mle$tau)))
  if ("rho_o" %in% names(par_mle)) map$rho_o <- factor(NA)

  args <- list(...)
  args$data <- data
  args$spatialCovs <- spatialCovs
  args$model <- fit$conditions$model
  args$par <- par_mle
  args$map <- map
  args$scaleFactor <- scaleFactor
  args$barrier <- fit$conditions$barrier
  args$lambda <- fit$conditions$lambda
  args$initialInner <- FALSE

  message("   Running post-hoc prediction via iterative TMB inner optimization...")
  message("   Iteration 1...")

  pred_fit <- suppressWarnings(suppressMessages(do.call(fitLangevin, args)))

  curr_mu_scaled <- t(pred_fit$tmb_setup$parList$mu)
  curr_mu_natural <- curr_mu_scaled * scaleFactor

  if ("vel" %in% names(pred_fit$tmb_setup$parList)) {
    curr_vel_scaled <- t(pred_fit$tmb_setup$parList$vel)
    curr_vel_natural <- curr_vel_scaled * scaleFactor
  }

  prev_raw_shift <- Inf
  damping_factor <- 1.0

  if (max_iter > 1) {
    for (i in 2:max_iter) {
      message(sprintf("   Iteration %d...", i))

      args$par$mu <- curr_mu_natural
      if ("vel" %in% names(pred_fit$tmb_setup$parList)) args$par$vel <- curr_vel_natural

      pred_try <- try({suppressWarnings(suppressMessages(do.call(fitLangevin, args)))}, silent = TRUE)

      if(!inherits(pred_try,"try-error")){

        pred_fit <- pred_try

        prev_mu_scaled <- curr_mu_scaled
        raw_new_mu_scaled <- t(pred_fit$tmb_setup$parList$mu)

        raw_step <- raw_new_mu_scaled - prev_mu_scaled
        raw_shift <- max(abs(raw_step))

        # --- AGGRESSIVE ADAPTIVE DAMPING ---
        if (exists("prev_raw_step")) {
          dir_check <- sum(raw_step * prev_raw_step)
          if (dir_check < 0) {
            # We bounced. Cut the damping factor in half (No artificial floor!)
            damping_factor <- damping_factor * 0.5
            message(sprintf("      Limit cycle detected. Reducing step size to %.3f%%", damping_factor * 100))
          } else if (dir_check > 0 && raw_shift < prev_raw_shift) {
            # If moving smoothly, gently accelerate back up to a max of 1.0
            damping_factor <- min(1.0, damping_factor * 1.1)
          }
        }
        prev_raw_step <- raw_step

        # Apply the aggressively damped step
        curr_mu_scaled <- prev_mu_scaled + (damping_factor * raw_step)
        curr_mu_natural <- curr_mu_scaled * scaleFactor

        if ("vel" %in% names(pred_fit$tmb_setup$parList)) {
          prev_vel_scaled <- curr_vel_scaled
          raw_new_vel_scaled <- t(pred_fit$tmb_setup$parList$vel)

          raw_vel_step <- raw_new_vel_scaled - prev_vel_scaled
          curr_vel_scaled <- prev_vel_scaled + (damping_factor * raw_vel_step)
          curr_vel_natural <- curr_vel_scaled * scaleFactor
        }

        actual_shift <- max(abs(curr_mu_scaled - prev_mu_scaled))
        message(sprintf("      Max coordinate shift (scaled): %.6f", actual_shift))

        # Exit if absolute tolerance is met
        if (actual_shift < tol) {
          message("   Trajectory stabilized (tolerance met).")
          break
        }

        if (abs(raw_shift - prev_raw_shift) < 1e-6) {
          message("   Trajectory stabilized (no further improvement).")
          break
        }

        if (i == max_iter) {
          warning("Trajectory did not fully stabilize within max_iter limit. Consider increasing 'max_iter'.")
        }

        prev_raw_shift <- raw_shift
      } else {
        message("      Failed: ", attr(pred_try, "condition")$message)
        break
      }
    }
  }

  class(pred_fit) <- c("predLangevin", class(pred_fit))

  return(pred_fit)
}
