#' Predict unobserved locations from a fitted Langevin model
#'
#' @description
#' Generates predicted locations (and velocities, for the underdamped model) along with their standard errors at unobserved times. This function works by freezing the maximum likelihood estimates of the movement and observation parameters from a previously fitted model and running an inner optimization to predict the latent locations.
#'
#' @param fit A \code{fitLangevin} object.
#' @param data A \code{dataLangevin} object generated by \code{\link{formatData}}. To predict unobserved times, this dataset must have been formatted with the \code{predTimes} argument so that it contains padded \code{NA} observations at the desired prediction times.
#' @param spatialCovs List of named \code{\link[terra]{SpatRaster-class}} objects containing the spatial covariates. Must be the exact same list used to fit the model.
#' @param ... Additional arguments passed to \code{\link{fitLangevin}}, e.g., \code{calcSE} to toggle standard error calculation, \code{inner.control} to govern the TMB optimizer, \code{par} to supply custom starting values for the locations (\code{par$mu}) and/or velocities (\code{par$vel}), or \code{map} to supply fixed values for the locations (\code{map$mu}) and/or velocities (\code{map$vel}).
#'
#' @details
#' This function provides an efficient way to interpolate animal tracks (e.g., along a regular temporal grid) after the primary model has been fitted on unpadded data. The fixed parameters are frozen and \code{TMB} optimizes over the random effects, allowing for imputation of the missing locations.
#'
#' @return A \code{fitLangevin} object containing the predicted trajectory. The structure is identical to a standard fitted model (with the addition of a \code{predLangevin} class), allowing it to be passed to \code{\link{plot.fitLangevin}} and other downstream functions.
#'
#' @export
predLangevin <- function(fit, data, spatialCovs, ...) {

  if (missing(data) || !inherits(data, "dataLangevin")) stop("'data' must be provided and must be a formatted 'dataLangevin' object.")
  if (missing(spatialCovs) || !is.list(spatialCovs)) stop("'spatialCovs' must be provided as a list of SpatRaster objects.")
  if(!inherits(fit,"fitLangevin")) stop("'fit' must be of class 'fitLangevin'.")

  verify_signatures(fit, spatialCovs = spatialCovs)

  args <- list(...)

  scaleFactor <- fit$conditions$scaleFactor
  parList <- fit$tmb_setup$parList

  # Extract fixed parameters to be frozen
  par_mle <- list(
    beta = parList$beta,
    sigma = exp(parList$log_sigma) * scaleFactor
  )
  if (fit$conditions$model == "underdamped") par_mle$gamma <- exp(parList$log_gamma)

  parNames <- names(fit$par)
  if ("l_psi" %in% parNames) par_mle$psi <- exp(parList$l_psi)
  if ("l_tau" %in% parNames) par_mle$tau <- exp(parList$l_tau)
  if ("l_rho_o" %in% parNames) par_mle$rho_o <- 2 / (1 + exp(-parList$l_rho_o)) - 1

  if (!is.null(args$par$mu)) par_mle$mu <- args$par$mu
  if (fit$conditions$model == "underdamped" && !is.null(args$par$vel)) {
    par_mle$vel <- args$par$vel
  }

  map <- list(
    beta = factor(rep(NA, length(par_mle$beta))),
    sigma = factor(NA)
  )
  if (fit$conditions$model == "underdamped") map$gamma <- factor(NA)
  if ("psi" %in% names(par_mle)) map$psi <- factor(NA)
  if ("tau" %in% names(par_mle)) map$tau <- factor(rep(NA, length(par_mle$tau)))
  if ("rho_o" %in% names(par_mle)) map$rho_o <- factor(NA)

  if (!is.null(args$map$mu)) map$mu <- args$map$mu
  if (!is.null(args$map$vel)) map$vel <- args$map$vel

  args$data <- data
  args$spatialCovs <- spatialCovs
  args$model <- fit$conditions$model
  args$par <- par_mle
  args$map <- map
  args$scaleFactor <- scaleFactor
  args$barrier <- fit$conditions$barrier
  if(is.null(args$lambda)) args$lambda <- fit$conditions$lambda
  args$coord <- fit$conditions$coord
  args$smoothGradient <- fit$conditions$smoothGradient
  args$npoints <- fit$conditions$npoints
  args$curweight <- fit$conditions$curweight
  args$zetaScale <- fit$conditions$zetaScale
  args$prior <- fit$conditions$prior

  args$initialInner <- FALSE

  message("   Running post-hoc prediction via TMB inner optimization...")

  pred_fit <- do.call(fitLangevin, args)

  class(pred_fit) <- c("predLangevin", class(pred_fit))

  return(pred_fit)
}
