#' Calculate Bhattacharyya's Affinity between two \code{\link[terra]{SpatRaster-class}} objects
#'
#' This function calculates the Bhattacharyya's affinity (also known as the Bhattacharyya coefficient) between two rasters, which is a measure of similarity between two probability distributions. The rasters are first normalized to sum to 1 (to represent probability distributions), and then the affinity is calculated as the sum of the square root of the product of the two distributions across all cells.
#' If multi-layer rasters are provided, the affinity is calculated pairwise for each corresponding layer.
#'
#' @details
#' \strong{Convenience feature:} If either \code{r1} or \code{r2} is a multi-layer stack generated by \code{\link{getUD}} (which may include uncertainty layers like \code{UD_SE_delta} or \code{UD_CV_delta}), \code{rasterOverlap} will automatically isolate just the actual utilization distribution layers (\code{UD} or \code{log_UD}) before performing the calculation. This ensures Bhattacharyya's affinity is only applied to valid probability distributions.
#'
#' @param r1 A \code{\link[terra]{SpatRaster-class}} object. If any values are negative, \code{rasterOverlap} assumes \code{r1} is on the log scale, and the raster will be exponentiated before calculating the affinity (and a warning will be triggered).
#' @param r2 A \code{\link[terra]{SpatRaster-class}} object. If any values are negative, \code{rasterOverlap} assumes \code{r2} is on the log scale, and the raster will be exponentiated before calculating the affinity (and a warning will be triggered).
#' @return A numeric vector containing the Bhattacharyya's affinity for each layer, with values between 0 (no overlap) and 1 (identical distributions).
#' @examples
#' r1 <- getUD(exampleCovs, beta = c(-4, 6, 5, -0.1), log = FALSE, plot = FALSE)
#' r2 <- getUD(exampleCovs, beta = c(-3, 5, 4, -0.1), log = FALSE, plot = FALSE)
#'
#' rasterOverlap(r1, r2)
#' @importFrom terra compareGeom global nlyr
#' @export
rasterOverlap <- function(r1, r2) {

  if (!inherits(r1, "SpatRaster") || !inherits(r2, "SpatRaster")) {
    stop("Both inputs must be terra::SpatRaster objects.")
  }

  # if present, isolate the probability distribution (UD) and drop uncertainty layers
  filter_ud <- function(r) {
    nms <- names(r)
    if (any(nms %in% c("UD", "log_UD"))) {
      target_idx <- which(nms %in% c("UD", "log_UD"))
      return(r[[target_idx]])
    }
    return(r)
  }

  r1 <- filter_ud(r1)
  r2 <- filter_ud(r2)
  # -----------------------------------------

  if (!terra::compareGeom(r1, r2, stopOnError = FALSE)) {
    stop("Rasters do not have the same geometry (extent, resolution, or CRS). Please resample/project first.")
  }

  # verify identical number of layers
  if (terra::nlyr(r1) != terra::nlyr(r2)) {
    stop(sprintf("Rasters must have the same number of layers. r1 has %d layer(s) and r2 has %d layer(s).", terra::nlyr(r1), terra::nlyr(r2)))
  }

  # Extract minimums as a vector across all layers
  min_r1 <- terra::global(r1, "min", na.rm = TRUE)[, 1]
  if (any(!is.na(min_r1) & min_r1 < 0)) {
    warning("Negative values found in r1. Assuming log-scale and exponentiating.")
    r1 <- exp(r1)
  }

  min_r2 <- terra::global(r2, "min", na.rm = TRUE)[, 1]
  if (any(!is.na(min_r2) & min_r2 < 0)) {
    warning("Negative values found in r2. Assuming log-scale and exponentiating.")
    r2 <- exp(r2)
  }

  # Extract sums as vectors
  sum_r1 <- terra::global(r1, "sum", na.rm = TRUE)[, 1]
  sum_r2 <- terra::global(r2, "sum", na.rm = TRUE)[, 1]

  if (any(is.na(sum_r1)) || any(sum_r1 == 0) || any(is.na(sum_r2)) || any(sum_r2 == 0)) {
    stop("One or more layers in r1 or r2 sum to 0 or NA. Cannot normalize into a probability distribution.")
  }

  # terra natively divides each raster layer by its corresponding vector element
  p <- r1 / sum_r1
  q <- r2 / sum_r2

  pq_sqrt <- sqrt(p * q)

  # Extract final overlap sums as a vector
  bc_val <- terra::global(pq_sqrt, "sum", na.rm = TRUE)[, 1]

  # Name the output vector for clarity if the layers have names
  names(bc_val) <- names(r1)

  return(bc_val)
}
