# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulate_langevin_cpp <- function(model, nbAnimals, obsPerAnimal, dt_vec, gamma, sigma, beta, raster_data, initialPosition, barrier_dist, barrier_penalty) {
    .Call(`_langevinSSM_simulate_langevin_cpp`, model, nbAnimals, obsPerAnimal, dt_vec, gamma, sigma, beta, raster_data, initialPosition, barrier_dist, barrier_penalty)
}

measurementError_rcpp <- function(data, smaj_sd, smin_sd, eor, psi, knownError = FALSE) {
    .Call(`_langevinSSM_measurementError_rcpp`, data, smaj_sd, smin_sd, eor, psi, knownError)
}

measurementError_LS_rcpp <- function(data, x_sd, y_sd, tau_x, tau_y, rho_o, knownError = FALSE) {
    .Call(`_langevinSSM_measurementError_LS_rcpp`, data, x_sd, y_sd, tau_x, tau_y, rho_o, knownError)
}

extract_sdf_rcpp <- function(pts, barrier_dist, raster_extent, raster_resolution) {
    .Call(`_langevinSSM_extract_sdf_rcpp`, pts, barrier_dist, raster_extent, raster_resolution)
}

simulate_regionprob_cpp <- function(nSims, n_cells, n_layers, n_covs, beta_draws, cov_mats_list, mask_mat, show_progress) {
    .Call(`_langevinSSM_simulate_regionprob_cpp`, nSims, n_cells, n_layers, n_covs, beta_draws, cov_mats_list, mask_mat, show_progress)
}

simulate_ud_cpp <- function(nSims, n_cells, n_ud_layers, n_covs, beta_draws, cov_mats_list, show_progress) {
    .Call(`_langevinSSM_simulate_ud_cpp`, nSims, n_cells, n_ud_layers, n_covs, beta_draws, cov_mats_list, show_progress)
}

