# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulate_langevin_cpp <- function(model, nbAnimals, obsPerAnimal, timeStep, gamma, sigma, beta, raster_data, initialPosition) {
    .Call(`_langevinSSM_simulate_langevin_cpp`, model, nbAnimals, obsPerAnimal, timeStep, gamma, sigma, beta, raster_data, initialPosition)
}

measurementError_rcpp <- function(data, smaj_sd, smin_sd, eor, psi, model) {
    .Call(`_langevinSSM_measurementError_rcpp`, data, smaj_sd, smin_sd, eor, psi, model)
}

measurementError_LS_rcpp <- function(data, x_sd, y_sd, tau_x, tau_y, rho_o, model) {
    .Call(`_langevinSSM_measurementError_LS_rcpp`, data, x_sd, y_sd, tau_x, tau_y, rho_o, model)
}

